/*
RESPOSTAS DOS EXERCICIOS DE HERANÇA

1-A)NÃO SERIA POSSIVEL POIS A SENHA É UM DADO PRIVATE, SÓ CONSEGUIRIAMOS SE CHAMASSEMOS POR UM MÉTODO GET.
1-B)A MENSAGEM SÓ FOI IMPRESSA APENAS UMA VEZ.

2-A)APARECE SOMENTE UMA VEZ.
2-B)POR QUE ELE É INSTANCIADO DUAS VEZES.

3-A)NÃO POR QUE O CLASS CUSTUMER ESTÁ HERDANDO UMA PROPRIEDADE PRIVADA DE USER. 

4-A)A RESPOSTA ESTÁ NO INDEX.TS
5-A)A RESPOSTA ESTÁ NO INDEX.TS

RESPOSTAS DOS EXERCICIOS DE POLIFORMISMO

1-A)CONSEGUI IMPRIMIR TODOS OS DADOS, PORÉM NA FUNÇÃO DEVE-SE CHAMAR SEPARADO, MAS QUANDO CHAMAMOS O OBJETO SOMENTE
NAO APARECE O RESULTADO DA FUNÇÃO.
2-A)DIZ QUE NÃO É POSSIVEL CRIAR UMA INSTANCIA DE UMA CLASSE ABSTRATA.
2-B)SERÁ SOMENTE POSSIVEL SE TIRARMOS O ABSTRACT DA CLASSE.

*/